# qa/unreachable_classifier.py

import asyncio
import csv
import json

from app.utils.timing_util import elapsed_time


def classify_unreachable_reason(reason: str) -> str:
    r = reason.lower()

    if "dns resolution failed" in r or "getaddrinfo failed" in r:
        return "dns_error"

    if "cloudflare" in r:
        if "403" in r:
            return "blocked_by_cloudflare"
        if "409" in r:
            return "cloudflare_conflict"
        if "521" in r:
            return "origin_down_cloudflare"
        return "cloudflare_unknown"

    if "http 404" in r:
        return "http_404"

    if ".business.site" in r and "404" in r:
        return "google_business_404"

    if "serverdisconnectederror" in r:
        return "server_disconnected"

    if "ssl error" in r:
        return "ssl_error"

    if "timeout" in r:
        return "timeout"

    if "connection error" in r:
        return "connection_error"

    return "unknown"


@elapsed_time("classify_csv_to_json")
async def classify_csv_to_json(csv_path="bad_urls_report.csv", json_out="bad_urls_report.json"):
    """
    Read the CSV generated by qa_bad_urls.py and produce a JSON classification report.
    """
    results = []

    with open(csv_path, "r", encoding="utf-8") as f:
        reader: csv.DictReader = csv.DictReader(f)
        for row in reader:
            category = classify_unreachable_reason(row["reason"])
            results.append({
                "domain": row["domain"],
                "status": row["status"],
                "protocol": row["protocol"],
                "reason": row["reason"],
                "category": category,
            })

    with open(json_out, "w", encoding="utf-8") as f:
        json.dump(results, f, indent=2)

    print(f"CSV report written to {json_out}")

    return results


if __name__ == "__main__":
    asyncio.run(classify_csv_to_json())
