# qa/unreachable_classifier.py
import asyncio
import csv
import json
import logging
import re
from collections import defaultdict

from app.utils.logger_util import get_logger
from app.utils.timing_util import elapsed_time

STATUS_CODE_RE = re.compile(r"HTTP[:\s]+(\d{3})")

logger = get_logger()


def extract_status_codes(reason: str):
    """
    Extract all HTTP status codes from the reason string.
    Returns a list of integers (e.g., [404, 403]).
    """
    return [int(code) for code in STATUS_CODE_RE.findall(reason)]


def classify_reason(reason: str) -> str:
    r = reason.lower()

    # DNS / resolution failures
    if "dns resolution failed" in r or "getaddrinfo failed" in r:
        return "dns_error"

    # Timeout
    if "timeout" in r:
        return "timeout"

    # SSL
    if "ssl error" in r or "handshake failure" in r:
        return "ssl_error"

    # Server disconnected
    if "serverdisconnectederror" in r:
        return "server_disconnected"

    # Connection error
    if "connection error" in r:
        return "connection_error"

    # Cloudflare
    if "cloudflare" in r:
        if "403" in r:
            return "blocked_by_cloudflare"
        if "409" in r:
            return "cloudflare_conflict"
        if "521" in r:
            return "origin_down_cloudflare"
        return "cloudflare_unknown"

    # HTTP status codes
    codes = extract_status_codes(reason)
    if codes:
        return f"http_{codes[0]}"

    return "unknown"


@elapsed_time("classify_csv_to_json")
def job_wrapper():
    logger.info("Running unreachable classifier as standalone script")
    asyncio.run(classify_csv_to_json())


async def classify_csv_to_json(csv_path="qa/qa_bad_urls_report.csv", json_out="qa/qa_bad_urls_report.json"):
    return await classify_csv_to_json_sync(csv_path, json_out)


async def classify_csv_to_json_sync(csv_path, json_out):
    # noinspection GrazieInspection
    """
            Read the CSV generated by qa_bad_urls.py and produce a JSON dict:
            {
                "dns_error": [...],
                "http_404": [...],
                "blocked_by_cloudflare": [...],
                ...
            }
            """
    categories = defaultdict(list)
    with open(csv_path, "r", encoding="utf-8") as f:
        reader: csv.DictReader = csv.DictReader(f)
        for row in reader:
            domain = row["domain"]
            reason = row["reason"]
            category = classify_reason(reason)
            categories[category].append(domain)
    with open(json_out, "w", encoding="utf-8") as f:
        json.dump(categories, f, indent=2)
    logger.info(f"Classification JSON written to {json_out}")
    return categories


if __name__ == "__main__":
    job_wrapper()
